MAINTAINER WangFeihong

# RUN rm /etc/apt/sources.list
# # COPY sources.list /etc/apt/sources.list
#
# RUN apt-get update
# #RUN apt-get install -y apt-transport-https vim iproute2 net-tools build-essential ca-certificates curl wget software-properties-common
# RUN apt-get install -y apt-transport-https vim iproute2 net-tools ca-certificates curl wget software-properties-common
#
#
# #RUN add-apt-repository ppa:jonathonf/python-3.6
RUN apt-get update
# #RUN apt-get install -y python3.6
# #RUN apt install -y python3.6-dev
# #RUN apt install -y python3.6-venv
#
RUN apt-get -y install python3-pip
RUN apt-get -y install wget
# RUN python3.6 get-pip.py
#
ENV PYTHONIOENCODING=utf-8
#
RUN mkdir /code
#RUN cp -r ChatRoom chatroom/
#RUN git clone https://github.com/Adam0429/RESTful-API
WORKDIR /code
#
#RUN pip3 install Flask 
#RUN wget https://pypi.python.org/packages/11/b6/abcb525026a4be042b486df43905d6893fb04f05aac21c32c638e939e447/pip-9.0.1.tar.gz#md5=35f01da33009719497f01a4ba69d63c9
#RUN tar -zxvf pip-9.0.1.tar.gz
#RUN cd pip-9.0.1
#RUN python3 setup.py install 
#RUN pip3 install flask
RUN pip3 install pymysql
#RUN pip3 install json
RUN pip3 install django
